# Generated by Django 4.1.3 on 2023-07-07 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="weather", name="id",),
        migrations.AddField(
            model_name="weather",
            name="last_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weather",
            name="city",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
